export const GET_ALL_POKEMONS = 'GET_ALL_POKEMONS'
export const GET_POKEMONS_SUCCESS = 'GET_POKEMONS_SUCCESS'
export const GET_POKEMONS_ERROR = 'GET_POKEMONS_ERROR'

export const GET_POKEMON_DETAIL = 'GET_POKEMON_DETAIL'
export const GET_POKEMON_NAME = 'GET_POKEMON_NAME'

export const CREATE_POKEMON = 'GET_ALL_POKEMONS'
export const CREATE_POKEMON_SUCCESS = 'GET_POKEMONS_SUCCESS'
export const CREATE_POKEMON_ERROR = 'GET_POKEMONS_ERROR'

export const GET_TYPES = 'GET_TYPES'
export const GET_TYPES_POKEMONS= 'GET_TYPES_POKEMONS'

